/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import Model.Producto;
import Model.Venta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heber
 */
public class frmVenta extends javax.swing.JFrame {

    conexion con = new conexion();
    Connection connection;
    Statement st;
    ResultSet rs;
    ArrayList<Producto> lstproductos;    
    ArrayList<Venta> lstVenta = new ArrayList<>();
    DefaultTableModel tblProducto = new DefaultTableModel();
    
    float unitPrice ;
    int amount ;
    int max ;
    int idFactura;
    float total;
    int UpdateAmount;
    
    public frmVenta() {
        initComponents();
       lstproductos = getProductos();
       FillCbx();
       Price();
       UpdateTable();
       tblProducto.addColumn("CODIGO");
       tblProducto.addColumn("NOMBRE");
       tblProducto.addColumn("CANTIDAD");
       tblProducto.addColumn("TOTAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<Producto>();
        spnCantidad = new javax.swing.JSpinner();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblTotalCompra = new javax.swing.JLabel();
        btnSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PRODUCTO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CANTIDAD:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PRECIO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TOTAL:");

        cbxProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoActionPerformed(evt);
            }
        });

        spnCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantidadStateChanged(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrecio.setText("Q 00.00");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setText("Q 00.00");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/agregar.png"))); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total:");

        lblTotalCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalCompra.setText("Q 00.00");

        btnSale.setText("Realizar Pedido");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnCantidad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)
                                .addComponent(lblTotalCompra)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(lblTotal)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblPrecio)))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTotalCompra)
                    .addComponent(btnSale)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spnCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantidadStateChanged
        Price();
    }//GEN-LAST:event_spnCantidadStateChanged

    private void cbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoActionPerformed
        Price();
    }//GEN-LAST:event_cbxProductoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Venta venta = new Venta();        
        int id = Integer.parseInt(cbxProducto.getItemAt(cbxProducto.getSelectedIndex()).getCodigoProducto());
        
        venta.setCodigoProducto(id);
        venta.setNombre(cbxProducto.getItemAt(cbxProducto.getSelectedIndex()).getNombreProducto());
        venta.setCantidad(Integer.parseInt(spnCantidad.getValue().toString()));
        venta.setTotal(Pay(amount * unitPrice));
        venta.setPrecioU(unitPrice);
        
        if(!findSale(venta)){            
            lstVenta.add(venta);
        }
        
        UpdateTable();
        clean();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        idFactura = CreateBilling();
        for (int i = 0; i < tblVentas.getRowCount(); i++) {
            Producto producto = getProductoId((int) tblVentas.getValueAt(i, 0));
            int cantidad = (int) tblVentas.getValueAt(i, 2);
            UpdateAmount = producto.getCantidadProducto() - cantidad;
            AddSale(producto,cantidad);
        }
        dispose();
    }//GEN-LAST:event_btnSaleActionPerformed

    private int CreateBilling(){
        
        int generatedId = 0; 
        try {
    Date fechaActual = new Date();
    String sql = "insert into factura (idPedido, fecha, total) values (?, ?,?)";
    
    connection = con.gertConnection();
    PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    preparedStatement.setString(1,NumberBilling());	
    preparedStatement.setDate(2, new java.sql.Date(fechaActual.getTime()));
    preparedStatement.setDouble(3, total);
    
    int rowsAffected = preparedStatement.executeUpdate();
    
    if (rowsAffected > 0) {
        ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
        if (generatedKeys.next()) {
            generatedId = generatedKeys.getInt(1);
            JOptionPane.showMessageDialog(null, "Se ha guardado correctamente la factura");
        }
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo guardar la factura.");
    }
    
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
        return generatedId;
    }
    
    private void AddSale(Producto producto, int cantidadC){
        try{
            String sql = "insert into venta (codigoProducto, cantidad, total, idFactura) "
                + "values ('"+producto.getCodigoProducto()+"','"+cantidadC+"','"+total+"','"+idFactura+"')";
       
            connection = con.gertConnection();
            st = connection.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Se ha guardado correctamente el prodcuto");
            updateProducto(Integer.parseInt(producto.getCodigoProducto()));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void updateProducto(int idP){
    
        try{
            String sql = "update producto set cantidadProducto='"+UpdateAmount+"' where codigoProducto="+idP;
       
            connection = con.gertConnection();
            st = connection.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Se ha Actualizado correctamente el prodcuto");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }
    
    public ArrayList<Producto> getProductos() 
    {
        String sql = "select * from producto";
        ArrayList<Producto> lstProducto = new ArrayList<>();
        try{
            connection = con.gertConnection();
            st = connection.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                Producto producto = new Producto();
                producto.setCantidadProducto(rs.getInt("cantidadProducto"));
                producto.setCodigoProducto(rs.getString("codigoProducto"));
                producto.setDescripcion(rs.getString("descripcion"));
                producto.setNombreProducto(rs.getString("nombreProducto"));
                producto.setPrecioUnitario(rs.getFloat("precioUnitario"));
                lstProducto.add(producto);
                
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        return lstProducto;
    }
     
    private void FillCbx(){
        cbxProducto.removeAllItems();
        
        for (int i = 0; i < lstproductos.size(); i++) {
            cbxProducto.addItem(new Producto(lstproductos.get(i).getCodigoProducto(),lstproductos.get(i).getNombreProducto()
                    ,lstproductos.get(i).getPrecioUnitario(),lstproductos.get(i).getCantidadProducto(),
                    lstproductos.get(i).getDescripcion()));
        }
    }
    
    private void Price(){
        unitPrice = cbxProducto.getItemAt(cbxProducto.getSelectedIndex()).getPrecioUnitario();
        amount = Integer.parseInt(spnCantidad.getValue().toString());
        max = cbxProducto.getItemAt(cbxProducto.getSelectedIndex()).getCantidadProducto();
        lblPrecio.setText(Pay(unitPrice));
        lblTotal.setText(Pay(unitPrice*amount));
        SpinnerModel model = spnCantidad.getModel();
        ((SpinnerNumberModel) model).setMaximum(max);
        
    }
    
    private String Pay(float price){
        return "Q " + Math.round(price*100.0)/100.0;
    }
    
    private void UpdateTable(){
        
        while(tblProducto.getRowCount() > 0 ){
            tblProducto.removeRow(0);
        }
         total = 0;
        for(Venta v: lstVenta){
        
            Object venta[] = new Object[4];
            venta[0] = v.getCodigoProducto();
            venta[1] = v.getNombre();
            venta[2] = v.getCantidad();
            venta[3] = v.getTotal();  
            total = (float) (total + (v.getCantidad() *v.getPrecioU()));
            tblProducto.addRow(venta);
        }
        
        tblVentas.setModel(tblProducto);
        lblTotalCompra.setText(Pay(total));
    }
    
    private void clean(){
        unitPrice = 0;
        amount = 1;
        cbxProducto.setSelectedIndex(0);
        spnCantidad.setValue(1);
        Price();
        
    }
    
    private boolean findSale(Venta newSale){
        for (Venta v: lstVenta){
            if(v.getCodigoProducto() == newSale.getCodigoProducto()){
                int newAmount = v.getCantidad() + newSale.getCantidad();
                v.setCantidad(newAmount);
                v.setTotal(Pay(unitPrice *newAmount));
                return true;
            }
        }
        return false;
    }
    
    public Producto  getProductoId(int id) 
    {
        String sql = "select * from producto where codigoProducto = " + id;
        Producto lstProducto = new Producto();
        try{
            connection = con.gertConnection();
            st = connection.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                Producto producto = new Producto();
                producto.setCantidadProducto(rs.getInt("cantidadProducto"));
                producto.setCodigoProducto(rs.getString("codigoProducto"));
                producto.setDescripcion(rs.getString("descripcion"));
                producto.setNombreProducto(rs.getString("nombreProducto"));
                producto.setPrecioUnitario(rs.getFloat("precioUnitario"));
                lstProducto = producto;
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        return lstProducto;
    }

    private String NumberBilling(){
    String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder codigo = new StringBuilder();
        Random rand = new Random();

        for (int i = 0; i < 6; i++) {
            int indice = rand.nextInt(caracteres.length());
            char caracter = caracteres.charAt(indice);
            codigo.append(caracter);
        }

        return "#"+codigo.toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSale;
    private javax.swing.JComboBox<Producto> cbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalCompra;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
